import json
import logging
import uuid
import datetime
from db import get_connection, is_oracle

logger = logging.getLogger(__name__)

def safe_str(val):
    """Ensures val is clean string without encoding anomalies."""
    if val is None:
        return None
    if isinstance(val, str):
        return val
    return str(val)


def init_db():
    """Initializes and migrates database tables in Oracle XE or SQLite."""
    conn = get_connection()
    is_ora = is_oracle()
    cursor = conn.cursor()

    try:
        if is_ora:
            _init_oracle_tables(cursor, conn)
        else:
            _init_sqlite_tables(cursor, conn)
    except Exception as e:
        logger.error("Error during database initialization: %s", e)
    finally:
        cursor.close()
        conn.close()


def _init_oracle_tables(cursor, conn):
    """Initializes tables for Oracle Database."""
    cursor.execute("SELECT table_name FROM user_tables")
    existing_tables = {row[0].upper() for row in cursor.fetchall()}

    # 1. USERS table
    if "USERS" not in existing_tables:
        cursor.execute("""
            CREATE TABLE users (
                user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR2(150) NOT NULL,
                email VARCHAR2(150) UNIQUE NOT NULL,
                password VARCHAR2(255) NOT NULL,
                created_date DATE DEFAULT SYSDATE,
                preferred_lang VARCHAR2(20) DEFAULT 'auto',
                theme VARCHAR2(20) DEFAULT 'dark'
            )
        """)
        conn.commit()
        logger.info("Oracle table 'USERS' created")
    else:
        cursor.execute("SELECT column_name FROM user_tab_columns WHERE table_name = 'USERS'")
        existing_cols = {row[0].upper() for row in cursor.fetchall()}
        if "PREFERRED_LANG" not in existing_cols:
            try:
                cursor.execute("ALTER TABLE users ADD preferred_lang VARCHAR2(20) DEFAULT 'auto'")
                conn.commit()
            except Exception:
                pass
        if "THEME" not in existing_cols:
            try:
                cursor.execute("ALTER TABLE users ADD theme VARCHAR2(20) DEFAULT 'dark'")
                conn.commit()
            except Exception:
                pass

    # 2. CONVERSATIONS table
    if "CONVERSATIONS" not in existing_tables:
        cursor.execute("""
            CREATE TABLE conversations (
                conversation_id VARCHAR2(64) PRIMARY KEY,
                user_email VARCHAR2(150) NOT NULL,
                title VARCHAR2(300) NOT NULL,
                model VARCHAR2(100) DEFAULT 'gemini-2.5-flash',
                is_pinned NUMBER(1) DEFAULT 0,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.commit()
        logger.info("Oracle table 'CONVERSATIONS' created")

    # 3. MESSAGES table
    if "MESSAGES" not in existing_tables:
        cursor.execute("""
            CREATE TABLE messages (
                message_id VARCHAR2(64) PRIMARY KEY,
                conversation_id VARCHAR2(64) NOT NULL,
                sender VARCHAR2(20) NOT NULL,
                content CLOB NOT NULL,
                attachments_json CLOB,
                citations_json CLOB,
                chart_data_json CLOB,
                forensics_json CLOB,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                token_count NUMBER DEFAULT 0
            )
        """)
        conn.commit()
        logger.info("Oracle table 'MESSAGES' created")

    # 4. DOCUMENTS table
    if "DOCUMENTS" not in existing_tables:
        cursor.execute("""
            CREATE TABLE documents (
                doc_id VARCHAR2(64) PRIMARY KEY,
                user_email VARCHAR2(150) NOT NULL,
                conversation_id VARCHAR2(64),
                filename VARCHAR2(300) NOT NULL,
                file_type VARCHAR2(50) NOT NULL,
                file_size NUMBER NOT NULL,
                file_path VARCHAR2(500) NOT NULL,
                page_count NUMBER DEFAULT 1,
                status VARCHAR2(50) DEFAULT 'ready',
                metadata_json CLOB,
                uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        conn.commit()
        logger.info("Oracle table 'DOCUMENTS' created")

    # 5. DOCUMENT_CHUNKS table (for RAG)
    if "DOCUMENT_CHUNKS" not in existing_tables:
        cursor.execute("""
            CREATE TABLE document_chunks (
                chunk_id VARCHAR2(64) PRIMARY KEY,
                doc_id VARCHAR2(64) NOT NULL,
                chunk_index NUMBER NOT NULL,
                page_number NUMBER DEFAULT 1,
                content CLOB NOT NULL,
                metadata_json CLOB
            )
        """)
        conn.commit()
        logger.info("Oracle table 'DOCUMENT_CHUNKS' created")


def _init_sqlite_tables(cursor, conn):
    """Initializes tables for SQLite."""
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users (
            user_id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            email TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL,
            created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            preferred_lang TEXT DEFAULT 'auto',
            theme TEXT DEFAULT 'dark'
        )
    """)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS conversations (
            conversation_id TEXT PRIMARY KEY,
            user_email TEXT NOT NULL,
            title TEXT NOT NULL,
            model TEXT DEFAULT 'gemini-2.5-flash',
            is_pinned INTEGER DEFAULT 0,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS messages (
            message_id TEXT PRIMARY KEY,
            conversation_id TEXT NOT NULL,
            sender TEXT NOT NULL,
            content TEXT NOT NULL,
            attachments_json TEXT,
            citations_json TEXT,
            chart_data_json TEXT,
            forensics_json TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            token_count INTEGER DEFAULT 0
        )
    """)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS documents (
            doc_id TEXT PRIMARY KEY,
            user_email TEXT NOT NULL,
            conversation_id TEXT,
            filename TEXT NOT NULL,
            file_type TEXT NOT NULL,
            file_size INTEGER NOT NULL,
            file_path TEXT NOT NULL,
            page_count INTEGER DEFAULT 1,
            status TEXT DEFAULT 'ready',
            metadata_json TEXT,
            uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS document_chunks (
            chunk_id TEXT PRIMARY KEY,
            doc_id TEXT NOT NULL,
            chunk_index INTEGER NOT NULL,
            page_number INTEGER DEFAULT 1,
            content TEXT NOT NULL,
            metadata_json TEXT
        )
    """)
    conn.commit()
    logger.info("SQLite tables initialized")


# ==========================================================
# Database Operation Helpers
# ==========================================================

def get_user_by_email(email):
    """Fetches user record by email."""
    conn = get_connection()
    is_ora = is_oracle()
    cursor = conn.cursor()
    try:
        if is_ora:
            cursor.execute("SELECT column_name FROM user_tab_columns WHERE table_name = 'USERS'")
            cols = [row[0].upper() for row in cursor.fetchall()]
            
            has_lang = "PREFERRED_LANG" in cols
            has_theme = "THEME" in cols
            
            query = "SELECT user_id, name, email, password, created_date"
            if has_lang:
                query += ", preferred_lang"
            if has_theme:
                query += ", theme"
            query += " FROM users WHERE email = :1"
            
            cursor.execute(query, (email,))
            row = cursor.fetchone()
            if row:
                user_dict = {
                    "user_id": row[0],
                    "name": row[1],
                    "email": row[2],
                    "password": row[3],
                    "created_date": str(row[4]),
                    "preferred_lang": "auto",
                    "theme": "dark"
                }
                idx = 5
                if has_lang and len(row) > idx:
                    user_dict["preferred_lang"] = row[idx] or "auto"
                    idx += 1
                if has_theme and len(row) > idx:
                    user_dict["theme"] = row[idx] or "dark"
                return user_dict
        else:
            cursor.execute("SELECT * FROM users WHERE email = ?", (email,))
            row = cursor.fetchone()
            if row:
                return dict(row)
        return None
    finally:
        cursor.close()
        conn.close()


def create_user(name, email, password):
    """Creates a new user record."""
    conn = get_connection()
    is_ora = is_oracle()
    cursor = conn.cursor()
    try:
        if is_ora:
            cursor.execute(
                "INSERT INTO users (name, email, password, created_date) VALUES (:1, :2, :3, SYSDATE)",
                (safe_str(name), safe_str(email), safe_str(password))
            )
        else:
            cursor.execute(
                "INSERT INTO users (name, email, password) VALUES (?, ?, ?)",
                (name, email, password)
            )
        conn.commit()
        return True
    finally:
        cursor.close()
        conn.close()


def get_user_conversations(user_email):
    """Retrieves all conversations for a user ordered by updated_at desc."""
    conn = get_connection()
    is_ora = is_oracle()
    cursor = conn.cursor()
    try:
        if is_ora:
            cursor.execute(
                "SELECT conversation_id, user_email, title, model, is_pinned, created_at, updated_at "
                "FROM conversations WHERE user_email = :1 ORDER BY is_pinned DESC, updated_at DESC",
                (user_email,)
            )
            rows = cursor.fetchall()
            return [
                {
                    "conversation_id": r[0],
                    "user_email": r[1],
                    "title": r[2],
                    "model": r[3],
                    "is_pinned": bool(r[4]),
                    "created_at": str(r[5]),
                    "updated_at": str(r[6])
                }
                for r in rows
            ]
        else:
            cursor.execute(
                "SELECT * FROM conversations WHERE user_email = ? ORDER BY is_pinned DESC, updated_at DESC",
                (user_email,)
            )
            rows = cursor.fetchall()
            return [dict(r) for r in rows]
    finally:
        cursor.close()
        conn.close()


def create_conversation(user_email, title="New Chat", model="gemini-2.5-flash"):
    """Creates a new conversation."""
    conv_id = str(uuid.uuid4())
    conn = get_connection()
    is_ora = is_oracle()
    cursor = conn.cursor()
    try:
        safe_title = safe_str(title)[:290]
        if is_ora:
            cursor.execute(
                "INSERT INTO conversations (conversation_id, user_email, title, model, is_pinned, created_at, updated_at) "
                "VALUES (:1, :2, :3, :4, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)",
                (conv_id, user_email, safe_title, model)
            )
        else:
            cursor.execute(
                "INSERT INTO conversations (conversation_id, user_email, title, model, is_pinned) "
                "VALUES (?, ?, ?, ?, 0)",
                (conv_id, user_email, safe_title, model)
            )
        conn.commit()
        return conv_id
    finally:
        cursor.close()
        conn.close()


def update_conversation(conversation_id, title=None, is_pinned=None, model=None):
    """Updates conversation metadata."""
    conn = get_connection()
    is_ora = is_oracle()
    cursor = conn.cursor()
    try:
        if is_ora:
            if title is not None:
                cursor.execute("UPDATE conversations SET title = :1, updated_at = CURRENT_TIMESTAMP WHERE conversation_id = :2", (safe_str(title)[:290], conversation_id))
            if is_pinned is not None:
                cursor.execute("UPDATE conversations SET is_pinned = :1, updated_at = CURRENT_TIMESTAMP WHERE conversation_id = :2", (1 if is_pinned else 0, conversation_id))
            if model is not None:
                cursor.execute("UPDATE conversations SET model = :1, updated_at = CURRENT_TIMESTAMP WHERE conversation_id = :2", (model, conversation_id))
        else:
            if title is not None:
                cursor.execute("UPDATE conversations SET title = ?, updated_at = CURRENT_TIMESTAMP WHERE conversation_id = ?", (title, conversation_id))
            if is_pinned is not None:
                cursor.execute("UPDATE conversations SET is_pinned = ?, updated_at = CURRENT_TIMESTAMP WHERE conversation_id = ?", (1 if is_pinned else 0, conversation_id))
            if model is not None:
                cursor.execute("UPDATE conversations SET model = ?, updated_at = CURRENT_TIMESTAMP WHERE conversation_id = ?", (model, conversation_id))
        conn.commit()
    finally:
        cursor.close()
        conn.close()


def delete_conversation(conversation_id):
    """Deletes conversation and all its messages and chunks."""
    conn = get_connection()
    is_ora = is_oracle()
    cursor = conn.cursor()
    try:
        if is_ora:
            cursor.execute("DELETE FROM messages WHERE conversation_id = :1", (conversation_id,))
            cursor.execute("DELETE FROM documents WHERE conversation_id = :1", (conversation_id,))
            cursor.execute("DELETE FROM conversations WHERE conversation_id = :1", (conversation_id,))
        else:
            cursor.execute("DELETE FROM messages WHERE conversation_id = ?", (conversation_id,))
            cursor.execute("DELETE FROM documents WHERE conversation_id = ?", (conversation_id,))
            cursor.execute("DELETE FROM conversations WHERE conversation_id = ?", (conversation_id,))
        conn.commit()
    finally:
        cursor.close()
        conn.close()


def save_message(conversation_id, sender, content, attachments=None, citations=None, chart_data=None, forensics=None):
    """Saves a message to the database."""
    msg_id = str(uuid.uuid4())
    att_json = json.dumps(attachments, ensure_ascii=False) if attachments else None
    cit_json = json.dumps(citations, ensure_ascii=False) if citations else None
    chart_json = json.dumps(chart_data, ensure_ascii=False) if chart_data else None
    forensics_json = json.dumps(forensics, ensure_ascii=False) if forensics else None

    conn = get_connection()
    is_ora = is_oracle()
    cursor = conn.cursor()
    try:
        safe_content = safe_str(content)
        if is_ora:
            cursor.execute(
                "INSERT INTO messages (message_id, conversation_id, sender, content, attachments_json, citations_json, chart_data_json, forensics_json, created_at) "
                "VALUES (:1, :2, :3, :4, :5, :6, :7, :8, CURRENT_TIMESTAMP)",
                (msg_id, conversation_id, sender, safe_content, att_json, cit_json, chart_json, forensics_json)
            )
            cursor.execute("UPDATE conversations SET updated_at = CURRENT_TIMESTAMP WHERE conversation_id = :1", (conversation_id,))
        else:
            cursor.execute(
                "INSERT INTO messages (message_id, conversation_id, sender, content, attachments_json, citations_json, chart_data_json, forensics_json) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
                (msg_id, conversation_id, sender, safe_content, att_json, cit_json, chart_json, forensics_json)
            )
            cursor.execute("UPDATE conversations SET updated_at = CURRENT_TIMESTAMP WHERE conversation_id = ?", (conversation_id,))
        conn.commit()
        return msg_id
    except Exception as e:
        logger.warning("save_message note: %s", e)
        return msg_id
    finally:
        cursor.close()
        conn.close()


def get_conversation_messages(conversation_id):
    """Retrieves all messages for a given conversation."""
    conn = get_connection()
    is_ora = is_oracle()
    cursor = conn.cursor()
    try:
        if is_ora:
            cursor.execute(
                "SELECT message_id, conversation_id, sender, content, attachments_json, citations_json, chart_data_json, forensics_json, created_at "
                "FROM messages WHERE conversation_id = :1 ORDER BY created_at ASC",
                (conversation_id,)
            )
            rows = cursor.fetchall()
            result = []
            for r in rows:
                content_str = r[3].read() if hasattr(r[3], 'read') else str(r[3])
                att_str = r[4].read() if hasattr(r[4], 'read') else r[4]
                cit_str = r[5].read() if hasattr(r[5], 'read') else r[5]
                chart_str = r[6].read() if hasattr(r[6], 'read') else r[6]
                for_str = r[7].read() if hasattr(r[7], 'read') else r[7]
                result.append({
                    "message_id": r[0],
                    "conversation_id": r[1],
                    "sender": r[2],
                    "content": content_str,
                    "attachments": json.loads(att_str) if att_str else [],
                    "citations": json.loads(cit_str) if cit_str else [],
                    "chart_data": json.loads(chart_str) if chart_str else None,
                    "forensics": json.loads(for_str) if for_str else None,
                    "created_at": str(r[8])
                })
            return result
        else:
            cursor.execute("SELECT * FROM messages WHERE conversation_id = ? ORDER BY created_at ASC", (conversation_id,))
            rows = cursor.fetchall()
            result = []
            for r in rows:
                item = dict(r)
                item["attachments"] = json.loads(item["attachments_json"]) if item.get("attachments_json") else []
                item["citations"] = json.loads(item["citations_json"]) if item.get("citations_json") else []
                item["chart_data"] = json.loads(item["chart_data_json"]) if item.get("chart_data_json") else None
                item["forensics"] = json.loads(item["forensics_json"]) if item.get("forensics_json") else None
                result.append(item)
            return result
    finally:
        cursor.close()
        conn.close()


def save_document(user_email, filename, file_type, file_size, file_path, page_count=1, conversation_id=None, metadata=None):
    """Saves document record."""
    doc_id = str(uuid.uuid4())
    meta_json = json.dumps(metadata, ensure_ascii=False) if metadata else "{}"

    conn = get_connection()
    is_ora = is_oracle()
    cursor = conn.cursor()
    try:
        if is_ora:
            cursor.execute(
                "INSERT INTO documents (doc_id, user_email, conversation_id, filename, file_type, file_size, file_path, page_count, status, metadata_json, uploaded_at) "
                "VALUES (:1, :2, :3, :4, :5, :6, :7, :8, 'ready', :9, CURRENT_TIMESTAMP)",
                (doc_id, user_email, conversation_id, safe_str(filename), file_type, file_size, safe_str(file_path), page_count, meta_json)
            )
        else:
            cursor.execute(
                "INSERT INTO documents (doc_id, user_email, conversation_id, filename, file_type, file_size, file_path, page_count, status, metadata_json) "
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'ready', ?)",
                (doc_id, user_email, conversation_id, filename, file_type, file_size, file_path, page_count, meta_json)
            )
        conn.commit()
        return doc_id
    finally:
        cursor.close()
        conn.close()


def get_user_documents(user_email):
    """Retrieves all documents for a user."""
    conn = get_connection()
    is_ora = is_oracle()
    cursor = conn.cursor()
    try:
        if is_ora:
            cursor.execute(
                "SELECT doc_id, user_email, conversation_id, filename, file_type, file_size, file_path, page_count, status, metadata_json, uploaded_at "
                "FROM documents WHERE user_email = :1 ORDER BY uploaded_at DESC",
                (user_email,)
            )
            rows = cursor.fetchall()
            docs = []
            for r in rows:
                meta_str = r[9].read() if hasattr(r[9], 'read') else r[9]
                docs.append({
                    "doc_id": r[0],
                    "user_email": r[1],
                    "conversation_id": r[2],
                    "filename": r[3],
                    "file_type": r[4],
                    "file_size": r[5],
                    "file_path": r[6],
                    "page_count": r[7],
                    "status": r[8],
                    "metadata": json.loads(meta_str) if meta_str else {},
                    "uploaded_at": str(r[10])
                })
            return docs
        else:
            cursor.execute("SELECT * FROM documents WHERE user_email = ? ORDER BY uploaded_at DESC", (user_email,))
            rows = cursor.fetchall()
            docs = []
            for r in rows:
                d = dict(r)
                d["metadata"] = json.loads(d["metadata_json"]) if d.get("metadata_json") else {}
                docs.append(d)
            return docs
    finally:
        cursor.close()
        conn.close()


def get_document_by_id(doc_id):
    """Retrieves document by ID."""
    conn = get_connection()
    is_ora = is_oracle()
    cursor = conn.cursor()
    try:
        if is_ora:
            cursor.execute(
                "SELECT doc_id, user_email, conversation_id, filename, file_type, file_size, file_path, page_count, status, metadata_json, uploaded_at "
                "FROM documents WHERE doc_id = :1",
                (doc_id,)
            )
            r = cursor.fetchone()
            if r:
                meta_str = r[9].read() if hasattr(r[9], 'read') else r[9]
                return {
                    "doc_id": r[0],
                    "user_email": r[1],
                    "conversation_id": r[2],
                    "filename": r[3],
                    "file_type": r[4],
                    "file_size": r[5],
                    "file_path": r[6],
                    "page_count": r[7],
                    "status": r[8],
                    "metadata": json.loads(meta_str) if meta_str else {},
                    "uploaded_at": str(r[10])
                }
        else:
            cursor.execute("SELECT * FROM documents WHERE doc_id = ?", (doc_id,))
            r = cursor.fetchone()
            if r:
                d = dict(r)
                d["metadata"] = json.loads(d["metadata_json"]) if d.get("metadata_json") else {}
                return d
        return None
    finally:
        cursor.close()
        conn.close()


def delete_document(doc_id):
    """Deletes document and its chunks."""
    conn = get_connection()
    is_ora = is_oracle()
    cursor = conn.cursor()
    try:
        if is_ora:
            cursor.execute("DELETE FROM document_chunks WHERE doc_id = :1", (doc_id,))
            cursor.execute("DELETE FROM documents WHERE doc_id = :1", (doc_id,))
        else:
            cursor.execute("DELETE FROM document_chunks WHERE doc_id = ?", (doc_id,))
            cursor.execute("DELETE FROM documents WHERE doc_id = ?", (doc_id,))
        conn.commit()
    finally:
        cursor.close()
        conn.close()


def save_document_chunks(doc_id, chunks):
    """Saves a batch of chunks for a document."""
    conn = get_connection()
    is_ora = is_oracle()
    cursor = conn.cursor()
    try:
        for i, chunk in enumerate(chunks):
            chunk_id = str(uuid.uuid4())
            page_num = chunk.get("page", 1)
            content = safe_str(chunk.get("text", ""))
            meta_json = json.dumps(chunk.get("metadata", {}), ensure_ascii=False)

            if is_ora:
                cursor.execute(
                    "INSERT INTO document_chunks (chunk_id, doc_id, chunk_index, page_number, content, metadata_json) "
                    "VALUES (:1, :2, :3, :4, :5, :6)",
                    (chunk_id, doc_id, i, page_num, content, meta_json)
                )
            else:
                cursor.execute(
                    "INSERT INTO document_chunks (chunk_id, doc_id, chunk_index, page_number, content, metadata_json) "
                    "VALUES (?, ?, ?, ?, ?, ?)",
                    (chunk_id, doc_id, i, page_num, content, meta_json)
                )
        conn.commit()
    finally:
        cursor.close()
        conn.close()


def get_document_chunks(doc_id):
    """Retrieves all chunks for a document."""
    conn = get_connection()
    is_ora = is_oracle()
    cursor = conn.cursor()
    try:
        if is_ora:
            cursor.execute("SELECT chunk_id, doc_id, chunk_index, page_number, content, metadata_json FROM document_chunks WHERE doc_id = :1 ORDER BY chunk_index ASC", (doc_id,))
            rows = cursor.fetchall()
            return [
                {
                    "chunk_id": r[0],
                    "doc_id": r[1],
                    "chunk_index": r[2],
                    "page_number": r[3],
                    "content": r[4].read() if hasattr(r[4], 'read') else str(r[4]),
                    "metadata": json.loads(r[5].read() if hasattr(r[5], 'read') else r[5]) if r[5] else {}
                }
                for r in rows
            ]
        else:
            cursor.execute("SELECT * FROM document_chunks WHERE doc_id = ? ORDER BY chunk_index ASC", (doc_id,))
            rows = cursor.fetchall()
            result = []
            for r in rows:
                item = dict(r)
                item["metadata"] = json.loads(item["metadata_json"]) if item.get("metadata_json") else {}
                result.append(item)
            return result
    finally:
        cursor.close()
        conn.close()
